// Try-catch block to handle error
try {
    throw new Error("Something went wrong");
}
catch (error) {
    console.log(error.message); // Logs the error message
}
